version: "3.9"
services:
  db:
    container_name: db
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/admin.sql:/docker-entrypoint-initdb.d/2.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/3.sql
#      - ./sql/data-pl.sql:/docker-entrypoint-initdb.d/3.sql
    restart: always
    environment:
      MYSQL_DATABASE: project_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - netw

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
    networks:
      - netw

  project-manager:
    container_name: project-manager
    build:
      context: ./
      dockerfile: ./project-manager/Dockerfile
    image: project-manager:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: 'always'
    networks:
      - netw
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/project_manager?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=CET
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  nginx:
    container_name: nginx
    image: nginx
    restart: 'always'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./project-manager-ui/build:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - netw
    depends_on:
      - project-manager
networks:
  netw:

volumes:
  db_data: