version: "3.9"
services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    #      - sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
    #      - sql/scripts.sql:/docker-entrypoint-initdb.d/2.sql
    restart: always
    environment:
      MYSQL_DATABASE: project_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - netw

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
    networks:
      - netw

networks:
  netw:

volumes:
  db_data: