version: "3.9"
services:
#  postgres:
#    container_name: postgres
#    image: postgres:11
#    restart: always
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      - POSTGRES_DB=project-manager
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "5432:5432"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: project_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
#      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql
#      - ./sql/scripts.sql:/docker-entrypoint-initdb.d/2.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1